name: CD Pipeline

on:
  workflow_run:
    workflows: [CI - Integration tests]
    types: [completed]
    
permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    strategy:
      matrix:
        node-version: [18.x] # Removed newer versions on assumption we'll just use version from repo
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['6.0']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present

      - name: Make artifact directory
        run: mkdir -p ./artifacts/${{ github.repository }}

      - name: Create Zip File
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -r ./artifacts/${{ github.repository }}/app.zip ./

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125485281:role/github-test
          aws-region: eu-west-2

      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync ./artifacts/${{ github.repository }}/ s3://catherine-bucket --delete
      
 #     - name: S3 to EC2 
#     run: | 
   #       aws deploy create-deployment --application-name catherinej-app --deployment-group-name production --s3-location bucket=catherine-bucket,key=app.zip,bundleType=zip
