name: CI - Integration tests

on:
  workflow_run:
    workflows: [CI - Unit tests]
    types: [completed]

jobs:
  ci-integration-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        node-version: [18.x] # Removed newer versions on assumption we'll just use version from repo
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v4 # checkout fetches the repo code into workflow env
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm install   
    - run: npm ci 
    
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
          start: npm run start:test
          wait-on: http://localhost:3030
