name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci: # Run linter and run tests (Jest and Cypress)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Removed newer versions on assumption we'll just use version from repo
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v4 # checkout fetches the repo code into workflow env
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm install   
    - run: npm ci 
    # - run: npm run build --if-present  # We didn't have a build section - leave out?
    - run: npm run lint
    - run: npm run test:unit
    
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
          start: npm run start:test
          wait-on: http://localhost:3030
